### ISSUE TITLE
bibtexparser and field limits

### ISSUE THREAD

**Issue by steog88** [steog88/PhysBiblio#1]
Traceback (most recent call last):
File "/home/gariazzo/software/PhysBiblio/physbiblio/gui/BibWindows.py", line 766, in updateBibkey
element = bibtexparser.loads(bibtex).entries[0]
File "/usr/local/lib/python3.5/dist-packages/bibtexparser/__init__.py", line 48, in loads
return parser.parse(bibtex_str)
File "/usr/local/lib/python3.5/dist-packages/bibtexparser/bparser.py", line 151, in parse
raise exc
File "/usr/local/lib/python3.5/dist-packages/bibtexparser/bparser.py", line 147, in parse
self._expr.parseFile(bibtex_file_obj)
File "/usr/local/lib/python3.5/dist-packages/bibtexparser/bibtexexpression.py", line 263, in parseFile
return self.main_expression.parseFile(file_obj, parseAll=True)
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1511, in parseFile
raise exc
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1505, in parseFile
return self.parseString(file_contents, parseAll)
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1125, in parseString
raise exc
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1119, in parseString
se._parse( instring, loc )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1046, in _parseCache
value = self._parseNoCache( instring, loc, doActions, callPreParse )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 989, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 2378, in parseImpl
loc, exprtokens = e._parse( instring, loc, doActions )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 1046, in _parseCache
value = self._parseNoCache( instring, loc, doActions, callPreParse )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 993, in _parseNoCache
loc,tokens = self.parseImpl( instring, preloc, doActions )
File "/usr/lib/python3/dist-packages/pyparsing.py", line 2183, in parseImpl
raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text (at char 0), (line:1, col:1)

**Comment by steog88** [comment]
It was just an old bibtexparser version.
Update with `pip install --upgrade bibtexparser `
